name: Tests

on:
  push:
    branches:
      - main
      - dev-integrate
  pull_request:
    branches:
      - main
      - dev-integrate

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.9]

    services:
      neo4j:
        image: sennet/neo4j:5.20.0
        ports:
          - 7474:7474
          - 7687:7687
        volumes:
          - ${{ github.workspace }}/docker/test/neo4j/neo4j.conf:/usr/src/app/neo4j/conf/neo4j.conf

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r src/requirements.dev.txt
      - name: Setup test config file
        run: |
          cp test/config/app.test.cfg src/instance/app.cfg
      - name: Test with pytest
        env:
          UBKG_SERVER: ${{ secrets.UBKG_SERVER }}
          UBKG_ENDPOINT_VALUESET: ${{ secrets.UBKG_ENDPOINT_VALUESET }}
          UBKG_CODES: ${{ secrets.UBKG_CODES }}
        run: |
          pytest -W ignore::DeprecationWarning 
