name: Tests

on:
  push:
    branches: [ 108-integrate-entity-api-pyunit-tests-with-github-actions ]
  pull_request:
    branches: [ 108-integrate-entity-api-pyunit-tests-with-github-actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Setup test config file
        run: |
          cp test/config/app.cfg src/instance/app.cfg
      - name: Test with pytest
        run: |
          pytest -W ignore::DeprecationWarning 
