name: Tests

on:
  push:
    branches:
      - main
      - dev-integrate
  pull_request:
    branches:
      - main
      - dev-integrate

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Run tests in docker
        env:
          UBKG_SERVER: ${{ secrets.UBKG_SERVER }}
          UBKG_ENDPOINT_VALUESET: ${{ secrets.UBKG_ENDPOINT_VALUESET }}
          UBKG_CODES: ${{ secrets.UBKG_CODES }}
        run: |
          ./run_tests.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
